### ISSUE TITLE
Its not an issue, just improvement

### ISSUE THREAD

**Issue by mishailovic** [danielwohlgemuth/pi-lcd-weather#1]
I made a layout specifically for my raspberry pi 3, could you add it to help other people
Here is a link to download it: https://ibb.co/QYRt2zk
I'll also attach it
![Raspberry pi display_bb 2](https://user-images.githubusercontent.com/41520056/60385594-5c3ecb80-9a93-11e9-93e7-d30818e77a1d.png)

**Comment by danielwohlgemuth** [comment]
I've added it. Thank you for submitting.
